# Generated by Django 4.1.3 on 2023-02-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('gen', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Nonbinary')])),
                ('vet', models.BooleanField()),
                ('has_children', models.BooleanField()),
            ],
        ),
    ]
