# Generated by Django 4.1.7 on 2023-03-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0003_location_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nabbed_bed', models.BooleanField(default=False)),
                ('no_room', models.BooleanField(default=False)),
                ('no_show', models.BooleanField(default=False)),
                ('not_liked', models.BooleanField(default=False)),
                ('unwelcome', models.BooleanField(default=False)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='shelter_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
