# Generated by Django 4.1.3 on 2023-03-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0004_demographics_alter_location_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Nonbinary')], default=1),
        ),
    ]
