# Generated by Django 4.1.7 on 2023-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0004_survey_alter_location_phone_and_more'),
        ('NeedABedAPI', '0005_location_lat_location_lon_alter_demographics_gender'),
    ]

    operations = [
    ]
