# Generated by Django 4.1.7 on 2023-03-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0006_merge_20230327_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='image',
        ),
    ]
