# Generated by Django 4.1.3 on 2023-03-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0007_remove_tester_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
    ]
