# Generated by Django 4.1.3 on 2023-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0008_location_is_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bed_count',
            field=models.IntegerField(default=0),
        ),
    ]
