# Generated by Django 4.1.3 on 2023-04-06 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0010_location_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='close_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name='location',
            name='open_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='location',
            name='shelter_type',
            field=models.CharField(choices=[('SH', 'Shelter'), ('WC', 'Warming Center'), ('DC', 'Detox Center'), ('YS', 'Youth Shelter'), ('WT', 'Wet Shelter'), ('FS', 'Family Shelter'), ('WS', "Women's Shelter")], default='SH', max_length=2),
        ),
    ]
