# Generated by Django 4.1.3 on 2023-04-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeedABedAPI', '0011_location_close_time_location_open_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelter',
        ),
        migrations.DeleteModel(
            name='tester',
        ),
    ]
